---
title: "Chapter 8"
author: "Nick Lauerman"
output: html_document
---

***

Graphs are included in a seperate code block, when needed, to allow caching of data within the 
markdown enviroment allowing to reduced time to execute and complile the page.

***

```{rglobal_options, include=FALSE}
knitr::opts_chunk$set(tidy=FALSE)
# change Drive letter for home (F:/) or work (E:/) locations
```
## setup
```{r libraries}
library(plotrix)
library(ggplot2)
library(lattice)
library(car)
library(plyr)
```


# Chapter 8
## section 8.2
```{r section 8.2 calculation 1, cache=TRUE, cache.path="E:/Baseball/cache/"}
Batting <- read.csv("E:/Baseball/data/lahman/Batting.csv")
Master  <- read.csv("E:/Baseball/data/lahman/Master.csv")

mantle.info <- subset(Master,
                      nameFirst == "Mickey" & nameLast == "Mantle")
mantle.id <- as.character(mantle.info$playerID)
require(car)
Batting$SF <- recode(Batting$SF, "NA = 0")
Batting$HBP <- recode(Batting$HBP, "NA - 0")

get.birthyear <- function(player.id){
     playerline <- subset(Master,
                          playerID == player.id)
     birthYear <- playerline$birthYear
     birthMonth <- playerline$birthMonth
     ifelse(birthMonth >= 7, birthYear + 1, birthYear)
}

# check should return 1932
get.birthyear(mantle.id)

get.stats <- function(player.id){
     d <- subset(Batting,
                 playerID == player.id)
     byear <- get.birthyear(player.id)
     d$Age <- d$yearID - byear
     d$SLG  <- with(d, (H - X2B - X3B - HR + 2 * X2B + 3 * X3B + 4 * HR) / AB)
     d$OBP  <- with(d, (H + BB) / (H + AB + BB + SF))
     d$OPS  <- with(d, SLG + OBP)
     d
}

Mantle <- get.stats(mantle.id)
```
```{r section 7.3 plots 1}
with(Mantle, plot(Age, OPS,
                  cex = 1.5,
                  pch = 19))
```
```{r section 8.2 calculation 2, cache=TRUE, cache.path="E:/Baseball/cache/"}
fit.model <- function(d){
     fit <- lm(OPS ~ I(Age - 30) + I((Age - 30)^2),
               data = d)
     b <- coef(fit)
     Age.max <- 30 - b[2] / b[3] / 2
     Max <- b[1] - b[2]^2 / b[3] / 4
     list(fit = fit,
          Age.max = Age.max,
          Max = Max)
}

F2 <- fit.model(Mantle)
coef(F2$fit)
c(F2$Age.max, F2$Max)
```
```{r section 7.3 plots 2}
with(Mantle, plot(Age, OPS,
                  cex = 1.5,
                  pch = 19))
lines(Mantle$Age,
      predict(F2$fit,
              Age = Mantle$Age),
      lwd = 3)
abline(v = F2$Age.max,
       lwd = 3,
       lty = 2,
       col = "grey")
abline(h = F2$Max,
       lwd = 3,
       lty = 2,
       col = "grey")
text(29.5, 0.72,
     "Peak age",
     cex = 2.0)
text(20, 1,
     "Max",
     cex = 2.0)

summary(F2$fit)
```

## Section 8.3
### Section 8.3.1
```{r section 8.3.1, cache=TRUE, cache.path="E:/Baseball/cache/"}
Fielding <- read.csv("E:/Baseball/data/lahman/Fielding.csv")

require(plyr)

AB.totals <- ddply(Batting, .(playerID),
                   summarize,
                   CareerAB = sum(AB, na.rm = TRUE))
Batting <- merge(Batting, AB.totals)
Batting.2000 <- subset(Batting,
                       CareerAB >= 2000)
# start
find.position <- function(p){
     positions <- c("OF",
                    "1B",
                    "2B",
                    "3B",
                    "C",
                    "P",
                    "DH")
     d <- subset(Fielding, playerID == p)
     count.games <- function(po){
          sum(subset(d, POS == po)$G)
     }
     FLD <- sapply(positions, count.games)
     positions[FLD == max(FLD)][1]
}

PLAYER <- as.character(unique(Batting.2000$playerID))
POSITIONS <- sapply(PLAYER, find.position)

Fielding.2000 <- data.frame(playerID = names(POSITIONS),
                            POS = POSITIONS)
Batting.2000 <- merge(Batting.2000, Fielding.2000)

```

### Section 8.3.2
```{r section 8.3.2, cache=TRUE, cache.path="E:/Baseball/cache/"}
require(plyr)
C.totals <- ddply( Batting.2000, .(playerID),
                   summarize,
                   C.G = sum(G, na.rm=TRUE),
                   C.AB = sum(AB, na.rm=TRUE),
                   C.R = sum(R, na.rm=TRUE),
                   C.H = sum(H, na.rm=TRUE),
                   C.2B = sum(X2B, na.rm=TRUE),
                   C.3B = sum(X3B, na.rm=TRUE),
                   C.HR = sum(HR, na.rm=TRUE),
                   C.RBI = sum(RBI, na.rm=TRUE),
                   C.BB = sum(BB, na.rm=TRUE),
                   C.SO = sum(SO, na.rm=TRUE),
                   C.SB = sum(SB, na.rm=TRUE))
C.totals$C.AVG <- with(C.totals, C.H / C.AB)
C.totals$C.SLG <- with(C.totals, 
                       (C.H - C.2B - C.3B - C.HR + 2 * C.2B + 3 * C.3B + 4 * C.HR) / C.AB)
C.totals <- merge(C.totals, Fielding.2000)
C.totals$Value.POS <- with(C.totals,
                              ifelse(POS == "C", 240,
                                ifelse(POS == "SS", 168,
                                  ifelse(POS == "2B", 132,
                                    ifelse(POS == "3B", 84,
                                      ifelse(POS == "OF", 48,
                                        ifelse(POS == "1B", 12, 0)))))))
```

# Section 8.3.3
```{r section 8.3.3, cache=TRUE, cache.path="E:/Baseball/cache/" }
similar <- function(p, number=10){
     P <- subset(C.totals, playerID == p)
     C.totals$SS <- with(C.totals,
                         1000 -
                         floor(abs(C.G -   P$C.G) / 20) -
                         floor(abs(C.AB -  P$C.AB) / 75) -
                         floor(abs(C.R -   P$C.R) / 10) -
                         floor(abs(C.H -   P$C.H) / 15) -
                         floor(abs(C.2B -  P$C.2B) / 5) -
                         floor(abs(C.3B -  P$C.3B) / 4) -
                         floor(abs(C.HR -  P$C.HR) / 2) -
                         floor(abs(C.RBI - P$C.RBI) / 10) -
                         floor(abs(C.BB -  P$C.BB) / 25) -
                         floor(abs(C.SO -  P$C.SO) / 150) -
                         floor(abs(C.SB -  P$C.SB) / 20) -
                         floor(abs(C.AVG - P$C.AVG) / 0.001) -
                         floor(abs(C.SLG - P$C.SLG) / 0.002) -
                         abs(Value.POS - P$Value.POS))
     C.totals <- C.totals[order(C.totals$SS, decreasing = TRUE), ]
     C.totals[1:number, ]
}

similar(mantle.id, 6)

```

### Section 8.3.4
```{r section 8.3.4, cache=TRUE, cache.path="E:/Baseball/cache/"}
collapse.stint <- function(d){
     G <- sum(d$G)
     AB <- sum(d$AB)
     R <- sum(d$R)
     H <- sum(d$H)
     X2B <- sum(d$X2B)
     X3B <- sum(d$X3B)
     HR <- sum(d$HR)
     RBI <- sum(d$RBI)
     SB <- sum(d$SB)
     CS <- sum(d$CS)
     BB <- sum(d$BB)
     SH <- sum(d$SH)
     SF <- sum(d$SF)
     HBP <- sum(d$HBP)
     SLG <- (H - X2B - X3B - HR + 2 * X2B + 3 * X3B + 4 * HR) / AB
     OBP <- (H + BB + HBP)/(AB + BB + HBP + SF)
     OPS <- SLG + OBP
     data.frame(G = G,
                AB = AB,
                R = R,
                H = H,
                X2B = X2B,
                X3B = X3B,
                HR = HR,
                RBI = RBI,
                SB = SB,
                CS = CS,
                BB = BB,
                HBP = HBP,
                SH = SH,
                SF = SF,
                SLG = SLG,
                OBP = OBP,
                OPS = OPS,
                Career.AB = d$CareerAB[1],
                POS = d$POS[1])
}

Batting.2000 <- ddply(Batting.2000,
                      .(playerID, yearID),
                      collapse.stint)

player.list <- as.character(unique(Batting.2000$playerID))
birthyears <- sapply(player.list, get.birthyear)
Batting.2000 <- merge(Batting.2000,
                      data.frame(playerID = player.list,
                                 Birthyear = birthyears))
Batting.2000$Age <- with(Batting.2000, yearID - Birthyear)

Batting.2000 <- Batting.2000[complete.cases(Batting.2000$Age),]
```

### Section 8.3.5
```{r section 8.3.5, cache=TRUE, cache.path="E:/Baseball/cache/" }
fit.trajectory <- function(d){
     fit <- lm(OPS ~ I(Age - 30) + I((Age - 30)^2),
               data = d)
     data.frame(Age = d$Age,
                Fit = predict(fit, Age = d$Age))
}

plot.trajectories <- function(first, last, n.similar=5, ncol){
     require(plyr)
     require(ggplot2)
     get.name <- function(playerid){
          d1 <- subset(Master, playerID == playerid)
          with(d1, paste(nameFirst, nameLast))
     }
     player.id <- subset(Master,
                         nameFirst == first & nameLast == last)$playerID
     player.id <- as.character(player.id)
     player.list <- as.character(similar(player.id, n.similar)$playerID)
     Batting.new <- subset(Batting.2000,
                           playerID %in% player.list)
     F2 <- ddply(Batting.new, .(playerID), fit.trajectory)
     F2 <- merge(F2,
                 data.frame(playerID = player.list,
                            Name = sapply(as.character(player.list), get.name)))
     print(ggplot(F2, aes(Age, Fit)) +
                       geom_line(size = 1.5) +
                       facet_wrap(~ Name, 
                                  ncol = ncol) +
                       theme_bw())
     return(Batting.new)
}
```
```{r section 8.3.5 plot 1}
d <- plot.trajectories("Mickey", "Mantle", 6, 2)

d <- plot.trajectories("Derek","Jeter", 9, 3)
```
```{r section 8.3.5 a, cache=TRUE, cache.path="E:/Baseball/cache/"}

summarize.trajectory <- function(d){
     f <- lm(OPS ~ I(Age -30) + I((Age - 30)^2),
             data = d)
     b <- coef(f)
     Age.max <- round(30 - b[2] / b[3] /2, 1)
     Max  <- round(b[1] - b[2]^2 / b[3] /4, 3)
     data.frame(Age.max = Age.max,
                Max = Max,
                Curve = round(b[3], 5))
}

S <- ddply(d, .(playerID),
           summarize.trajectory)
```
```{r section 8.3.5 plot 2}
with(S, plot(Age.max, Curve,
             pch = 19,
             cex = 1.5,
             xlab = "Peak Age",
             ylab = "Curvature",
             xlim = c(27, 36),
             ylim = c(-0.0035, 0)))
S$lastNames <- as.character(subset(Master,
                                   playerID %in% S$playerID)$nameLast)
with(S, text(Age.max, Curve,
             lastNames,
             pos = 3))
```

## Section 8.4
### Section 8.4.1
```{r section 8.4.1, cache=TRUE, cache.path="E:/Baseball/cache/"}
require(plyr)

midcareers <- ddply(Batting.2000, .(playerID),
                    summarize,
                    Midyear = (min(yearID) + max(yearID)) / 2)
Batting.2000 <- merge(Batting.2000, midcareers)
Batting.2000 <- na.omit(Batting.2000)
coefficients.trajectory <- function (d){
     b <- coef(lm(OPS ~ I(Age - 30) + I((Age - 30)^2),
                  data = d))
     a <-data.frame(A = b[1],
                B = b[2],
                C = b[3],
                MidYear = d$Midyear[1],
                Career.AB = d$Career.AB[1])
     return(a)
}
Beta.coef <- ddply(Batting.2000, .(playerID),
                  coefficients.trajectory)
Beta.coef$Peak.age <- with(Beta.coef, 30 - B /2 /C)
```

### Section 8.4.2
```{r section 8.4.2 plots}
with(Beta.coef,
     plot(MidYear, Peak.age,
          ylim = c(20, 40),
          xlab = "Mid Career",
          ylab = "Peak Age"))
i <- is.finite(Beta.coef$Peak.age)
with (Beta.coef,
      lines(lowess(MidYear[i],
                   Peak.age[i]),
            lwd = 3))
```

### Section 8.4.3
```{r section 8.4.3 plot}
with(Beta.coef,
     plot(log2(Career.AB[i]),
          Peak.age[i],
          ylim = c(20, 40),
          xlab = "log2 Career AB",
          ylab = "Peak Age"))
with(Beta.coef,
     lines(lowess(log2(Career.AB[i]),
                  Peak.age[i]),
                  lwd = 3))
```

## Section 8.5
```{r section 8.5, , cache=TRUE, cache.path="E:/Baseball/cache/"}
Batting.2000A <- subset(Batting.2000,
                        Midyear >= 1985 & Midyear <= 1995)

trajectory.peak.pos <- function(d){
     b <- coef(lm(OPS ~ I(Age - 30) + I((Age - 30)^2),
                  data = d))
     
     data.frame(A = b[1],
                B = b[2],
                C = b[3],
                Peak.Age = 30- b[2] / 2 / b[3],
                Position = d$POS[1])
}

Beta.estimates <- ddply(Batting.2000A,
                        .(playerID),
                        trajectory.peak.pos)
Beta.estimates1 <- subset(Beta.estimates,
                          Position %in% c("1B",
                                          "2B",
                                          "3B",
                                          "SS",
                                          "C",
                                          "OF"))
Beta.estimates1$Positions <- Beta.estimates1$Positions[ ,drop=TRUE]

Beta.estimates1 <- merge(Beta.estimates1, Master)
```
```{r section 8.5 plots}
stripchart(Peak.Age ~ Position,
           data = Beta.estimates1,
           xlim = c(20, 40),
           method = "jitter",
           pch = 1)

#special <- with(Beta.estimates1,
#                identify(Peak.Age, Position,
#                         n = 5,
#                         labels = nameLast))
special = c(52, 62, 75, 175, 181)
```
```{r section 8.5 a, , cache=TRUE, cache.path="E:/Baseball/cache/"}
dnew <- subset(Batting.2000,
               playerID %in% Beta.estimates1$playerID[special])

dnew <- merge(dnew, Master)
```
```{r section 8.5 plots a}
ggplot(dnew, aes(Age, OPS)) +
     geom_point(size = 4) +
     facet_wrap(~ nameLast, 
                ncol = 2) +
     ylim(0.4, 1.05) +
     theme_bw() +
     stat_smooth(method="lm",
                 se = FALSE,
                 size = 1.5,
                 formula = y ~ poly(x, 2, raw = TRUE)) 
```
