---
title: "Chapter 6"
author: "Nick Lauerman"
date: "Saturday, April 18, 2015"
output: html_document
---

***

Graphs are included in a seperate code block, when needed, to allow caching of data within the 
markdown enviroment allowing to reduced time to execute and complile the page.

***
```{rglobal_options, include=FALSE}
knitr::opts_chunk$set(tidy=FALSE)
```
## setup
```{r libraries}
# junk()
library(lattice)
library(ggplot2)
library(jpeg)
```

```{r setup, cache=TRUE, cache.path="E:/Baseball/cache/"}
# load("E:/Baseball/data/book/balls_strikes_count.RData") # home
load("E:/Baseball/data/book/balls_strikes_count.RData") # work
```

# Lattice graphics
## Section 6.2
### Section 6.2.2
```{r section 6.2.2, cache=TRUE, cache.path="E:/Baseball/cache/"}
sampleRows <- sample(1:nrow(verlander), 20)
verlander[sampleRows, ]
```

### Section 6.2.3
```{r section 6.2.3, fig.width=10}
histogram(~ speed, 
          data = verlander)
densityplot(~ speed,
            data = verlander,
            plot.points = FALSE)
```


### Section 6.2.4
```{r section 6.2.4, fig.width= 10}
densityplot(~speed | pitch_type,
            data = verlander,
            layout = c(1,5),
            plot.points = FALSE)
```

### Section 6.2.5
```{r section 6.2.5, fig.width=10}
densityplot(~ speed,
            data = verlander,
            groups = pitch_type,
            plot.points = FALSE,
            auto.key = TRUE)
```

### Section 6.2.6
```{r section 6.2.6 calulations, cache=TRUE, cache.path="E:/Baseball/cache/"}
F4verl <- subset(verlander, pitch_type == "FF")
F4verl$gameDay <- as.integer(format(F4verl$gamedate, format = "%j"))

dailySpeed <- aggregate(speed ~ gameDay + season, 
                        data = F4verl,
                        FUN = mean)
# time for first plot 

speedFC <- subset(verlander, 
                  pitch_type %in% c("FF" , "CH"))
avgspeedFC <- aggregate( speed ~ pitch_type + season,
                         data = speedFC,
                         FUN = mean)
avgspeedFC <- droplevels(avgspeedFC)
avgspeedFC

# time for second plot

```
```{r section 6.2.6 plots, fig.width=10}
# first plot
xyplot(speed ~ gameDay | factor(season),
       data = dailySpeed,
       xlab = "day of the year",
       ylab = "pitch speed (MPH)")

#second plot
dotplot(factor(season) ~ speed,
        group = pitch_type,
        data = avgspeedFC,
        pch = c("C","F"),
        cex = 2)
```

### Sectio 6.2.7


```{r section 6.2.7 calculations, cache=TRUE, cache.path="E:/Baseball/cache/"}
avgSpeed <- aggregate(speed ~ pitches + season,
                      data = F4verl,
                      FUN = mean)
# first plot
avgSpeedComb <- mean(F4verl$speed)



```
```{r section 6.2.7 plots, fig.width= 10}
# First Plot
xyplot(speed ~ pitches | factor(season),
       data = avgSpeed)

# Second plot
xyplot(speed ~ pitches | factor(season),
       data = avgSpeed,
       panel = function(...){
            panel.xyplot(...)
            panel.abline(v=100,
                         lty = "dotted")
            panel.abline(h = avgSpeedComb)
            panel.text(25, 100, "Avg. speed")
            panel.arrows(25, 99.5, 0,
                         avgSpeedComp,
                         length = 0.1)
            }
       )
```

### section 6.2.8
```{r section 6.2.8 calculations, cache=TRUE, cache.path="E:/Baseball/cache/"}
NoHit <- subset(verlander, gamedate == "2011-05-07")

# bulid 3 graphs

pitchnames <- list("change-up",
                  "curveball",
                  "4S-fastball",
                  "2S-fastball",
                  "slider")

myKey <- list(space = "right",
              border = TRUE,
              cex.title = 0.8,
              title = "pitch type",
              text = pitchnames,
              padding.text = 4)

topKzone <- 3.5
botKzone <- 1.6
inKzone <- -0.95
outKzone <- 0.95

# build final graph
```
```{r section 6.2.8 plots, fig.width= 10}
xyplot(pz ~ px | batter_hand,
       data = NoHit,
       groups = pitch_type,
       auto.key = TRUE)

xyplot(pz ~ px | batter_hand,
       data = NoHit,
       groups = pitch_type,
       auto.key = TRUE,
       aspect = "iso")

xyplot(pz ~ px | batter_hand,
       data = NoHit,
       groups = pitch_type,
       auto.key = TRUE,
       aspect = "iso",
       xlim = c(-2.2, 2.2),
       ylim = c(0, 5),
       xlab = "Horizontal Location\n(ft. from middle of plate)",
       ylab = "Vertical Loaction\n(ft. from ground)")

# the final plot
xyplot(pz ~ px | batter_hand,
       data = NoHit,
       groups = pitch_type,
       auto.key = TRUE,
       aspect = "iso",
       xlim = c(-2.2, 2.2),
       ylim = c(0, 5),
       xlab = "Horizontal Location\n(ft. from middle of plate)",
       ylab = "Vertical Loaction\n(ft. from ground)",
       panel = function (...){
            panel.xyplot(...)
            panel.rect(inKzone,
                       botKzone,
                       outKzone,
                       topKzone,
                       border = "black",
                       lty = 3)
       })

```

# ggplot
## section 6.3
### section 6.3.2

```{r section 6.3.2, cache=TRUE, cache.path="E:/Baseball/cache/"}
sampleRow <- sample(1:nrow(cabrera),20)
cabrera[sampleRow, ]
```

### Section 6.3.3
```{r section 6.3.3, cache=TRUE, cache.path="E:/Baseball/cache/"}
require(ggplot2)
p0 <- ggplot(data = cabrera,
             aes(x = hitx,
                 y = hity))

p1 <- p0 + geom_point()
```
```{r section 6.3.3 plots}
p1
```

### Section 6.3.4
```{r Section 6.3.4, cache=TRUE, cache.path="E:/Baseball/cache/"}
p1 <- p0 + geom_point(aes(color = hit_outcome))

p2 <- p1 + coord_equal()
```
```{r section 6.3.4 plots}
p2
```

### Section 6.3.5
```{r section 6.3.5}
p3 <- p2 + facet_wrap(~ season)
p3
```

### Section 6.3.6
```{r section 6.3.6}
bases <- data.frame(x = c(0,
                          90/sqrt(2),
                          0,
                          -90/sqrt(2),
                          0),
                    y = c(0,
                          90/sqrt(2),
                          2 * 90/sqrt(2),
                          90/sqrt(2),
                          0)
                    )
p4 <- p3 + geom_path(aes(x = x, y = y), data = bases)

p4 + geom_segment(x = 0, 
                  xend = 300,
                  y = 0,
                  yend = 300) +
     geom_segment(x = 0, 
                  xend = -300,
                  y = 0,
                  yend = 300)
```

### Section 6.3.7
```{r section 6.3.7}
cabreraStretch  <- subset(cabrera,
                          gamedate > "2012-08-31")
p0 <- ggplot(data = cabreraStretch,
             aes(hitx,
                 hity))
p1  <- p0 + geom_point(aes(shape = hit_outcome,
                           colour = pitch_type,
                           size = speed))
p2 <- p1 + coord_equal()
p3  <- p2 + geom_path(aes(x = x, y = y),
                      data = bases)
p4 <- p3 + guides(col = guide_legend(ncol = 2))
p4 + geom_segment(x = 0, 
                  xend = 300,
                  y = 0,
                  yend = 300) +
     geom_segment(x = 0, 
                  xend = -300,
                  y = 0,
                  yend = 300)
```

### Section 6.3.8
```{r section 6.3.8}
ggplot(F4verl, aes(pitches, speed)) +
     facet_wrap(~season) +
     geom_line(stat = "hline",
               yintercept = "mean",
               lty = 3) +
     geom_point(aes(pitches, speed),
                data = F4verl[sample(1:nrow(F4verl), 1000), ]) +
     geom_smooth(col = "black") +
     geom_vline(aes(xintercept = 100),
                    col = "black",
                    lty = 2)

```

### Section 6.3.9
```{r section 6.3.9}
kZone <- data.frame(
     x = c(inKzone, inKzone, outKzone, outKzone, inKzone),
     y = c(botKzone, topKzone, topKzone, botKzone, botKzone))

ggplot(F4verl, aes(px,pz)) +
     geom_point() +
     facet_wrap(~batter_hand) +
     coord_equal() +
     geom_path(aes(x, y),
               data = kZone,
               lwd = 2,
               col = "white")

ggplot(F4verl, aes(px,pz)) +
     stat_binhex() +
     facet_wrap(~batter_hand) +
     coord_equal() +
     geom_path(aes(x, y),
               data = kZone,
               lwd = 2,
               col = "white",
               alpha = 0.3)
```

### Section 6.3.10
```{r section 6.3.10}
require(jpeg)
diamond <- readJPEG("E:/Baseball/data/book/Comerica.jpg")

ggplot(cabrera, aes(hitx, hity)) +
     coord_equal() +
     annotation_raster(diamond, -310, 305, -100, 480) +
     stat_binhex(alpha = 0.9,
                    binwidth = c(5, 5)) +
     scale_fill_gradient(low = "grey70",
                         high = "black")
```

