---
title: "Chapter 7"
author: "Nick Lauerman"
output: html_document
---

***

Graphs are included in a seperate code block, when needed, to allow caching of data within the 
markdown enviroment allowing to reduced time to execute and complile the page.

***

```{rglobal_options, include=FALSE}
knitr::opts_chunk$set(tidy=FALSE)
# change Drive letter for home (F:/) or work (E:/) locations
```
## setup
```{r libraries}
library(plotrix)
library(lattice)
```


# Chapter 7
## section 7.2
### sectin 7.2.2
```{r section 7.2.2, cache=TRUE, cache.path="F:/Baseball/cache/"}
mussina <- expand.grid(balls = 0:3,
                       strikes = 0:2)
mussina$value <- c(100, 118, 157, 207, 72, 82, 114, 171, 30, 38, 62, 122)

countmap <- function(data){
     require(plotrix)
     data <- xtabs(value ~ .,
                   data)
     color2D.matplot(data,
                     show.values =2,
                     axes = FALSE,
                     xlab = "",
                     ylab = "")
     axis(side = 2,
          at = 3.5:0.5,
          labels = rownames(data),
          las = 1)
     axis(side = 3,
          at = 0.5:2.5,
          labels = colnames(data))
     mtext(text="balls",
           side = 2,
           line = 2,
           cex.lab = 1)
     mtext(text = "strikes",
           side = 3,
           line = 2,
           cex.lab = 1)
}
```
```{r section 7.2.2 plot}
countmap(mussina)
```

### Section 7.2.4

```{r section 7.2.4, cache=TRUE, cache.path="F:/Baseball/cache/"}
pbp11rc <- read.csv("F:/Baseball/data/book/pbp11rc.csv")
pbp11rc[1:5, c("GAME_ID",
               "EVENT_ID",
               "c00", "c10", "c20",
               "c11", "c01", "c30",
               "c21","c31","c02","c12","c22",
               "RUNS.VALUE")]

ab10 <- subset(pbp11rc, c10 == 1)
ab01 <- subset(pbp11rc, c01 == 1)

c(mean(ab10$RUNS.VALUE),
  mean(ab01$RUNS.VALUE))

runs.by.count <- expand.grid(balls = 0:3,
                             strikes = 0:2)
runs.by.count$value <- 0

bs.count.run.value <- function(b, s){
     column.name <- paste0("c",b,s)
     mean(pbp11rc[pbp11rc[ ,column.name]== 1, "RUNS.VALUE"])
}

runs.by.count$value <- mapply(FUN = bs.count.run.value,
                              b = runs.by.count$balls,
                              s = runs.by.count$strikes)
```
```{r section 7.2.4 plot}
countmap(runs.by.count)
```

### Section 7.2.5
```{r section 7.2.5, cache=TRUE, cache.path="F:/Baseball/cache/"}
count22 <- subset(pbp11rc, c22 == 1)
mean(count22$RUNS.VALUE)
count22$after2 <- ifelse(count22$c20 == 1, "2-0",
                         ifelse(count22$c02 == 1, "0-2" , "1-1"))
aggregate(RUNS.VALUE ~ after2,
          data = count22,
          FUN = mean)

count11 <- subset(pbp11rc, c11 == 1)
count11$after1  <- ifelse(count11$c10 == 1, "1-0", "0-1")
aggregate(RUNS.VALUE ~ after1,
          data = count11,
          FUN = mean)
```

## Section 7.3
```{r section 7.3, cache=TRUE, cache.path="F:/Baseball/cache/"}
load("F:/Baseball/data/book/balls_strikes_count.Rdata")
```

### Section 7.3.1
#### Sectin 7.3.1.1 
```{r section 7.3.1.1, cache=TRUE, cache.path="F:/Baseball/cache/"}
sampCabrera <- cabrera[sample(1:nrow(cabrera), 1000), ]
topKzone  <- 3.5
botKzone <- 1.6
inKzone <- -0.95
outKzone <- 0.95
```
```{r section 7.3.1.1 plot}
require(lattice)
xyplot(pz ~ px,
       data = sampCabrera,
       groups = swung,
       aspect = "iso",
       xlab = "horizontal location (ft.)",
       ylab =    "vertical locatin (ft.)",
       auto.key = list(point = TRUE,
                       text = c("not swung",
                                "swung"),
                       space = "right"),
       panel = function(...){
            panel.xyplot(...)
            panel.rect(inKzone,
                       botKzone,
                       outKzone,
                       topKzone,
                       border = "black")
       })
```
```{r section 7.3.1.1 calculation, cache=TRUE, cache.path="F:/Baseball/cache/"}
miggy.loess <- loess(swung ~ px + pz,
                     data = cabrera,
                     control = loess.control(surface = "direct"))

pred.area <- expand.grid(px = seq(-2, 2, 0.1),
                         pz = seq(0, 6, 0.1))

pred.area$fit <- c(predict(miggy.loess, pred.area))

# down Broadway
subset(pred.area,
       px == 0 & pz == 2.5)

# ball in the dirt
subset(pred.area,
       px == 0 & pz == 0)

# way outside
subset(pred.area,
       px == 2 & pz == 2.5)
```
```{r section 7.3.1.1 plot 2}
require(lattice)
contourplot(fit ~ px * pz,
            data = pred.area,
            at = c(0.2, 0.4, 0.6, 0.8),
            aspect = "iso",
            xlim = c(-2, 2),
            ylim = c(0, 5),
            ylab = "vertical location (ft.)",
            xlab = "horizontal location (ft.)",
            panel=function(...){
                 panel.contourplot(...)
                 panel.rect(inKzone,
                            botKzone,
                            outKzone,
                            topKzone,
                            border = "black",
                            lty = "dotted")
            })
```

#### Section 7.3.1.2
```{r section 7.3.1.2, cache=TRUE, cache.path="F:/Baseball/cache/"}
cabrera$bscount <- paste(cabrera$balls, cabrera$strikes, sep = "-")
miggy00 <- subset(cabrera, bscount == "0-0")
miggy00loess <- loess(swung ~ px + pz,
                      data = miggy00,
                      control = loess.control(surface = "direct"))
pred.area$fit00  <- c(predict(miggy00loess, pred.area))

miggy02 <- subset(cabrera, bscount == "0-2")
miggy02loess <- loess(swung ~ px + pz,
                      data = miggy02,
                      control = loess.control(surface = "direct"))
pred.area$fit02  <- c(predict(miggy02loess, pred.area))

miggy20 <- subset(cabrera, bscount == "2-0")
miggy20loess <- loess(swung ~ px + pz,
                      data = miggy20,
                      control = loess.control(surface = "direct"))
pred.area$fit20  <- c(predict(miggy20loess, pred.area))
```
```{r section 7.3.1.2 plot}
contourplot(fit00 + fit02 + fit20 ~ px * pz,
            data = pred.area,
            aspect = "iso",
            at = c(0.2, 0.4, 0.6, 0.8),
            xlim = c(-2, 2),
            ylim = c(0, 5),
            xlab = "horizontal location (ft.)",
            ylab = "vertical location (ft.)",
            main = "Cabrera location",
            panel = function (...){
                 panel.contourplot(...)
                 panel.rect(inKzone,
                            botKzone,
                            outKzone,
                            topKzone,
                            border = "black",
                            lty = "dotted")
            })
```

### Section 7.3.2
```{r section 7.3.2, cache=TRUE, cache.path="F:/Baseball/cache/"}
table(verlander$pitch_type)
round(100 * prop.table(table(verlander$pitch_type)))

type_verlander_hand <- with(verlander,
                            table(pitch_type,
                                  batter_hand))
round(100 * prop.table(type_verlander_hand,
                             margin = 2))

verlander$bscount <- paste(verlander$balls,
                          verlander$strikes,
                          sep = "-")
verl_RHB <- subset(verlander, batter_hand == "R")
verl_type_cnt_R <- table(verl_RHB$bscount,
                         verl_RHB$pitch_type)
round(100 * prop.table(verl_type_cnt_R, margin = 1))

verl_LHB <- subset(verlander, batter_hand == "L")
verl_type_cnt_L <- table(verl_LHB$bscount,
                         verl_LHB$pitch_type)
round(100 * prop.table(verl_type_cnt_L, margin = 1))
```

### section 7.3.3
```{r section 7.3.3 a}
umpireRHB <- subset(umpires, batter_hand == "R")
pred.area <- expand.grid(px = seq(-2, 2, 0.1),
                         pz = seq(0, 6, 0.1))
# model called strikes by location for three counts
# 0-0 count
ump00 <- subset(umpireRHB, 
                balls == 0 & strikes == 0)
ump00smp <- ump00[sample(1:nrow(ump00), 3000), ]
ump00.loess <- loess(called_strike ~ px + pz,
                     data = ump00smp,
                     control = loess.control(surface = "direct"))

# 3-0 count
ump30 <- subset(umpireRHB, 
                balls == 3 & strikes == 0)
ump30smp <- ump30[sample(1:nrow(ump30), 3000), ]
ump30.loess <- loess(called_strike ~ px + pz,
                     data = ump30smp,
                     control = loess.control(surface = "direct"))

# 0-2 count
ump02 <- subset(umpireRHB, 
                balls == 0 & strikes == 2)
ump02smp <- ump02[sample(1:nrow(ump02), 3000), ]
ump02.loess <- loess(called_strike ~ px + pz,
                     data = ump02smp,
                     control = loess.control(surface = "direct"))
```
```{r section 7.3.3 b}
# compute contours
# 0-0
ump00contour <- contourLines(x = seq(-2, 2, 0.1),
                             y = seq(0, 6, 0.1),
                             z = predict(ump00.loess,
                                         pred.area),
                             levels = c(0.5))
ump00df <- as.data.frame(ump00contour)
ump00df$bscount <- "0-0"


# 3-0
ump30contour <- contourLines(x = seq(-2, 2, 0.1),
                             y = seq(0, 6, 0.1),
                             z = predict(ump30.loess,
                                         pred.area),
                             levels = c(0.5))
ump30df <- as.data.frame(ump30contour)
ump30df$bscount <- "3-0"


# 0-2
ump02contour <- contourLines(x = seq(-2, 2, 0.1),
                             y = seq(0, 6, 0.1),
                             z = predict(ump02.loess,
                                         pred.area),
                             levels = c(0.5))
ump02df <- as.data.frame(ump02contour)
ump02df$bscount <- "0-2"

umpireContours <- rbind(ump00df,
                        ump02df,
                        ump30df)
```
```{r section test}

require(lattice)
trellis.par.set(theme = canonical.theme(color = FALSE))

myKey <- list(lines = TRUE,
              points = FALSE,
              space = "right",
              title = "balls/strikes count",
              cex.title = 1,
              padding = 4)
```
```{r section 7.3.3 plots}
xyplot(y ~ x,
       data = umpireContours,
       groups = bscount,
       type = "l",
       aspect = "iso",
       col = "black",
       xlim = c(-2, 2),
       ylim = c(0, 5),
       xlab = "horizontal location (ft.)",
       ylab = "vertical location (ft.)",
       auto.key = myKey,
       panel = function(...){
            panel.xyplot(...)
            panel.rect(inKzone,
                       botKzone,
                       outKzone,
                       topKzone,
                       border = "grey70",
                       lwd = 2)
       })
```

