---
title: "Chapter 5"
author: "Nick Lauerman"
output: html_document
---
```{rglobal_options, include=FALSE}
knitr::opts_chunk$set(tidy=FALSE)


```

# Section 5.2
```{r section 5.2, cache=TRUE, cache.path="E:/Baseball/cache/"}
data2011 <- read.csv("E:/Baseball/data/book/all2011.csv", header = FALSE) #WORK
fields <- read.csv("E:/Baseball/data/book/fields.csv")
names(data2011) <- fields[,"Header"]

data2011$RUNS <- with(data2011, AWAY_SCORE_CT + HOME_SCORE_CT)

data2011$HALF.INNING <- with(data2011, 
                             paste(GAME_ID,
                                   INN_CT,
                                   BAT_HOME_ID))

data2011$RUNS.SCORED <- with(data2011, (BAT_DEST_ID > 3) +
                                  (RUN1_DEST_ID > 3) +
                                  (RUN2_DEST_ID > 3 ) +
                                  (RUN3_DEST_ID > 3))

RUNS.SCORED.INNING <- aggregate(data2011$RUNS.SCORED,
                                list(HALF.INNING = data2011$HALF.INNING),
                                sum)

RUNS.SCORED.START <- aggregate(data2011$RUNS,
                               list(HALF.INNING = data2011$HALF.INNING),
                               "[", 1)

MAX <- data.frame(HALF.INNING = RUNS.SCORED.START$HALF.INNING)

MAX$x <- RUNS.SCORED.INNING$x + RUNS.SCORED.START$x

data2011 <- merge(data2011, MAX)

N <- ncol(data2011)
names(data2011)[N] <- "MAX.RUNS"

data2011$RUNS.ROI <- with(data2011,
                          MAX.RUNS - RUNS)
```

# Section 5.3
```{r section 5.3, cache=TRUE, cache.path="E:/Baseball/cache/"}
runner1 <- ifelse(as.character(data2011[ ,"BASE1_RUN_ID"]) == "", 0, 1)
runner2 <- ifelse(as.character(data2011[ ,"BASE2_RUN_ID"]) == "", 0, 1)
runner3 <- ifelse(as.character(data2011[ ,"BASE3_RUN_ID"]) == "", 0, 1)

get.state <- function(Runner1, Runner2, Runner3, Outs){
     Runners <- paste(Runner1, Runner2, Runner3, sep="")
     paste(Runners, Outs)
}

data2011$STATE <- get.state(runner1, runner2, runner3, data2011$OUTS_CT)

NRUNNER1 <- with(data2011, 
                 as.numeric(RUN1_DEST_ID == 1 | 
                                 BAT_DEST_ID == 1))

NRUNNER2 <- with(data2011,
                 as.numeric(RUN1_DEST_ID == 2 |
                                 RUN2_DEST_ID == 2 |
                                 BAT_DEST_ID == 2))
NRUNNER3 <- with(data2011,
                 as.numeric(RUN1_DEST_ID == 3 |
                                 RUN2_DEST_ID == 3 |
                                 RUN3_DEST_ID == 3 |
                                 BAT_DEST_ID == 3))

NOUTS <- with(data2011, OUTS_CT + EVENT_OUTS_CT)

data2011$NEW.STATE <- get.state(NRUNNER1, NRUNNER2, NRUNNER3, NOUTS)

data2011 <- subset(data2011, (STATE != NEW.STATE) | (RUNS.SCORED > 0))

library(plyr)
data.outs <- ddply(data2011,
                   .(HALF.INNING), 
                   summarize,
                   Outs.Inning = sum(EVENT_OUTS_CT))

data2011 <- merge(data2011, data.outs)

data2011C  <- subset(data2011, Outs.Inning == 3)

RUNS <- with(data2011C,
             aggregate(RUNS.ROI,
                       list(STATE),
                       mean))

RUNS$Outs  <- substr(RUNS$Group, 5, 5)
RUNS <- RUNS[order(RUNS$Outs) , ]


RUNS.out <- matrix(round(RUNS$x, 2), 8, 3)

dimnames(RUNS.out)[[2]] <- c("0 outs",
                             "1 outs",
                             "2 outs")
dimnames(RUNS.out)[[1]] <- c("000",
                             "001",
                             "010",
                             "011",
                             "100",
                             "101",
                             "110",
                             "111")
RUNS.2002 <- matrix(c(0.51, 1.40, 1.14, 1.96, 0.90, 1.84,
                      1.51, 2.33, 0.27, 0.94, 0.68, 1.36,
                      0.54, 1.18, 0.94, 1.51, 0.10, 0.36,
                      0.32, 0.63, 0.23, 0.52, 0.45, 0.78),
                    8, 3)
dimnames(RUNS.2002) <- dimnames(RUNS.out)

cbind(RUNS.out, RUNS.2002)
```

# Section 5.4
```{r section 5.4, cache=TRUE, cache.path="E:/Baseball/cache/"}
RUNS.POTENTIAL <- matrix(c(RUNS$x, rep(0,8)), 32, 1)

dimnames(RUNS.POTENTIAL)[[1]] <- c(RUNS$Group,
                                  "000 3",
                                  "001 3",
                                  "010 3",
                                  "011 3",
                                  "100 3",
                                  "101 3",
                                  "110 3",
                                  "111 3")
data2011$RUNS.STATE <- RUNS.POTENTIAL[data2011$STATE, ]
data2011$RUNS.NEW.STATE <- RUNS.POTENTIAL[data2011$NEW.STATE, ]
data2011$RUNS.VALUE <- with(data2011,
                            RUNS.NEW.STATE -
                                 RUNS.STATE +
                                 RUNS.SCORED)

```

#Section 5.5
```{r section 5.5, cache=TRUE, cache.path="E:/Baseball/cache/"}
#page 111
roster <- read.csv("E:/Baseball/data/book/roster2011.csv")  #WORK
albert.id <- subset(roster,
                    First.Name == "Albert" &
                         Last.Name == "Pujols")$Player.ID

albert.id <- as.character(albert.id)

albert <- subset(data2011, BAT_ID == albert.id)
albert <- subset(albert, BAT_EVENT_FL == TRUE)

albert[1:2, c("STATE",
              "NEW.STATE",
              "RUNS.VALUE")]

#page 112

albert$RUNNERS <- substr(albert$STATE, 1, 3)
table(albert$RUNNERS)
```

```{r 5.5 plot}
with(albert, stripchart(RUNS.VALUE ~ RUNNERS,
                        vertical = TRUE,
                        jitter = 0.2,
                        xlab = "Runners",
                        method = "jitter",
                        pch = 1,
                        cex = 0.8,
                        main = "Albert Pujols"))
abline(h=0)
```
```{r section 5.5 continued, cache=TRUE, cache.path="E:/Baseball/cache/"}
# page 113

A.runs <- aggregate(albert$RUNS.VALUE,
                    list(albert$RUNNERS),
                    sum)
names(A.runs)[2] <- "RUNS"

A.PA <- aggregate(albert$RUNS.VALUE,
                 list(albert$RUNNERS),
                 length)
names(A.PA)[2]  <- "PA"

A <- merge(A.PA, A.runs)
A

# page 114
sum(A$RUNS)
```

# Section 5.6
```{r section 5.6, cache=TRUE, cache.path="E:/Baseball/cache/"}
#pg 114
data2011b <- subset(data2011,
                   BAT_EVENT_FL == TRUE)

runs.sum <- aggregate(data2011b$RUNS.VALUE, 
                      list(data2011b$BAT_ID), 
                      sum)
runs.pa <- aggregate(data2011b$RUNS.VALUE, 
                     list(data2011b$BAT_ID), 
                     length)
runs.start <- aggregate(data2011b$RUNS.STATE, 
                        list(data2011b$BAT_ID), 
                        sum)

# pg 115
names(runs.sum) <- c("Batter","Runs")
names(runs.pa) <- c("Batter","PA")
names(runs.start) <- c("Batter","Runs.Start")

runs <- merge(runs.sum, runs.pa)
runs <- merge(runs, runs.start)

runs400 <- subset(runs, PA >= 400)
head(runs400)
```
```{r section 5.6 plots}
with(runs400, plot(Runs.Start, Runs))
with(runs400, lines(lowess(Runs.Start, Runs)))
abline(h=0)

# pg 116

runs400.top <- subset(runs400, Runs > 40)
runs400.top <- merge(runs400.top, roster,
                     by.x = "Batter",
                     by.y = "Player.ID")
with(runs400.top, text(Runs.Start, Runs,
                       Last.Name,
                       pos = 1))
```

# Section 5.7
```{r section 5.7, cache=TRUE, cache.path="E:/Baseball/cache/"}
# pg 116
get.batting.pos <- function(batter){
     TB <- table(subset(data2011,
                        BAT_ID == batter)$BAT_LINEUP_ID)
     names(TB)[TB == max(TB)][1]
}
position <- sapply(as.character(runs400$Batter),get.batting.pos)

AP <- subset(runs400, Batter == albert.id) # from pg 118 moved for RMarkdown flow
# pg 117
```
```{r section 5.7 plots}
with(runs400, plot(Runs.Start, Runs, type = "n"))
with(runs400, lines(lowess(Runs.Start, Runs)))
abline(h=0)
with(runs400, text(Runs.Start, Runs, position))

# pg 118


points(AP$Runs.Start, AP$Runs,
       pch = 4,
       cex = 3,
       col = "red")
```

# section 5.8
## 5.8.1
```{r section 5.8.1, cache=TRUE, cache.path="E:/Baseball/cache/"}
#119
d.homerun <- subset(data2011, EVENT_CD == 23)
table(d.homerun$STATE)
round(prop.table(table(d.homerun$STATE)), 3)

# from 121 for plots and cache
subset(d.homerun,
       RUNS.VALUE == max(RUNS.VALUE))[1, c("STATE",
                                           "NEW.STATE",
                                           "RUNS.VALUE")]
mean.HR <- mean(d.homerun$RUNS.VALUE)
mean.HR
```
```{r section 5.8.1 plots}
#120
library(MASS)
truehist(d.homerun$RUNS.VALUE, 
         xlab = "Runs Value",
         main = "RUns Value for Homeruns")
abline(v=mean.HR, lwd = 3)
text(1.5 ,5, 
     paste0("Mean Runs Value (",round(mean.HR, 3),")"), 
     pos = 4)

```

##5.8.2
```{r section 5.8.2, cache=TRUE, cache.path="E:/Baseball/cache/"}
d.single <- subset(data2011, EVENT_CD == 20)
table(d.single$STATE)
round(prop.table(table(d.single$STATE)), 3)
subset(d.single,
       RUNS.VALUE == max(d.single$RUNS.VALUE)
       )[ , c("STATE",
              "NEW.STATE",
              "RUNS.VALUE")]
subset(d.single,
       RUNS.VALUE == min(d.single$RUNS.VALUE)
       )[ , c("STATE",
              "NEW.STATE",
              "RUNS.VALUE")]
mean.single <- mean(d.single$RUNS.VALUE)
mean.single
```
```{r section 5.8.2 plots}
truehist(d.single$RUNS.VALUE,
         xlab = "Runs Value",
         main = "Runs Value for Singles")
abline(v=mean.single,
       lwd=3)
text(0.5, 5,
     paste0("Mean Runs Value (",round(mean.single, 3),")"),
     pos = 4)
```

# 5.9
```{r section 5.9, cache=TRUE, cache.path="E:/Baseball/cache/"}
stealing <- subset(data2011, EVENT_CD == 6 | EVENT_CD == 4)
table(stealing$EVENT_CD)
table(stealing$STATE)
```
```{r section 5.9 plots}
truehist(stealing$RUNS.VALUE,
         xlab = "Runs Value",
         main = "Runs Value for Stolen base")
```
```{r section 5.9 continued, cache=TRUE, cache.path="E:/Baseball/cache/"}
stealing.1001 <- subset(stealing, STATE == "100 1")
table(stealing.1001$EVENT_CD)
table(stealing.1001$NEW.STATE)
mean(stealing.1001$RUNS.VALUE)
```

